import swaggerJSDoc from 'swagger-jsdoc';
import swaggerAutogen from 'swagger-autogen';

const options = {
  swaggerDefinition: {
    // Swagger definition options
    openapi: '3.0.0',
    info: {
      title: 'My API',
      version: '1.0.0',
      description: 'API documentation for my app',
    },
    servers: [
      {
        url: '/api/v1',
      },
    ],
  },
  apis: [
    // List of files with Swagger annotations
    './routes/index.js',
    // './routes/freelancers.js',
    // './routes/freelancers.js',
    // './routes/freelancers.js',
  ],
};
const doc = {
  openapi: '3.0.0',
  info: {
    version: '1.0.0',
    title: 'My API',
    license: {
      name: 'Apache 2.0',
      url: 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'User',
      description: 'Endpoints',
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: 'apiKey',
      in: 'header', // can be "header", "query" or "cookie"
      name: 'X-API-KEY', // name of the header, query parameter or cookie
      description: 'any description...',
    },
  },
  definitions: {
    Parents: {
      father: 'Simon Doe',
      mother: 'Marie Doe',
    },
    User: {
      name: 'Jhon Doe',
      age: 29,
      parents: {
        $ref: '#/definitions/Parents',
      },
      diplomas: [
        {
          school: 'XYZ University',
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: 'XYZ Company',
          },
        },
      ],
    },
    AddUser: {
      $name: 'Jhon Doe',
      $age: 29,
      about: '',
    },
  },
};

const outputFile = './swagger_output.json';
const endpointsFiles = ['./routes/index.js'];
// swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
//   require('./index.js');
// });
const swaggerSpec = swaggerJSDoc(options);

// export default swaggerSpec;
